sudo: true

language: node_js
node_js:
  - 'stable'

script:
  - npm run prettier:check
  - npm install
  - npm run build
  - npm run export

deploy:
  skip_cleanup: true
  provider: script
  script: bash aws_deploy
  on:
    branch: master
