sudo: false

language: node_js
node_js:
  - "stable"
  
script:
  - npm install
  - npm run build
  - npm run export
  
deploy:
  provider: script
  script: bash aws_deploy
  on:
    branch: master