name: DDDEMWeb Build
on: [pull_request]

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10.x, 12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install packages
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Run Export
        run: npm run export

      - name: Run pa11y
        run: npm run pa11y
